name: Version Increment

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: paulhatch/semantic-version@v4.0.2
        id: next-version
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${increment}"
          short_tags: false

      - run: git config --global user.name 'AboutBits Tech'
      - run: git config --global user.email 'tech@aboutbits.it'
      - run: npm version {{steps.next-version.outputs.version}} -m "[RELEASE] {{ steps.next-version.outputs.version }}"
      - run: git push
