name: Version Increment

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: echo ${{ steps.package-version.outputs.current-version}}
